CREATE TABLE LOG_EVENTS (
   EVENT_ID VARCHAR(50) NOT NULL,
   EVENT_DURATION INTEGER NOT NULL,
   EVENT_TYPE VARCHAR (8),
   EVENT_HOST VARCHAR (50),
   ALERT BOOLEAN NOT NULL
   PRIMARY KEY (EVENT_ID)
);